
version: '3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
  v1:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

