version: '3'
services:
  db:
    image: mariadb

    restart: always

    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: task3
      MARIADB_USER: maya
      MARIADB_PASSWORD: 123
    
    networks:
      - my-network 
   
    volumes:
      - db_data:/var/lib/mysql

  v1:
    build: .

    ports:
      - "5000:5000"

    depends_on:
      - db

    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /data/db_data
      o: bind


