version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: galera-db1
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: task3
      MYSQL_SERVER_ID: 1
      MYSQL_CLUSTER_NAME: galera_cluster
      MYSQL_CLUSTER_ADDRESS: gcomm://10.0.2.4,10.0.2.5,10.0.2.6
    volumes:
      - db_data1:/var/lib/mysql
    networks:
      - my-network
    ports:
      - "3306:3306"
    command: --wsrep_cluster_address="gcomm://10.0.2.4,10.0.2.5,10.0.2.6" --wsrep_node_address="10.0.2.5"

  v1:
    image: 1maya1/training:v1
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    external: true
volumes:
  db_data1:
    driver: local
    driver_opts:
      type: none
      device: /data/db_data1
      o: bind

